# Generated by Django 4.2.8 on 2023-12-11 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Kayit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=20)),
                ("address", models.CharField(max_length=300)),
                ("city", models.CharField(max_length=255)),
                ("province", models.CharField(max_length=200)),
                ("country", models.CharField(max_length=200)),
            ],
        ),
    ]
